(Fix) messaging and signInWithPhoneNumber
NativeFirebaseError: [auth/notification-not-forwarded] If app delegate swizzling is disabled, remote notifications received by UIApplicationDelegate need to be forwarded to FIRAuth's canHandleNotificaton: method.
    at FirebaseAuthModule.signInWithPhoneNumber (http://192.168.0.167:8081/index.bundle?platform=ios&dev=true&minify=false:107323:28)