fix: linkWithCredential different behavior between Android and IOS
Description
When doing "linkWithCredential" in Android and the users exists relogin with this new user instead of launch exception 
Error: [auth/credential-already-in-use] This credential is already associated with a different user account.

Related issues